### ISSUE TITLE
Missing sgd_data.txt

### ISSUE THREAD

**Issue by tuhinmallick** [Arko98/Gradient-Descent-Algorithms#1]
Thanks for providing such a great implementations of various gradient descent algorithm. But for the example notebook, can you also provide the sgd_data.txt also ?

**Comment by Arko98** [comment]
HU @tuhinmallick,
Extremely sorry for the late reply. **sgd_data.txt** can be any (40,1) shaped numpy array converted into text file. Here we only need some sample data so that SGD can converge into it.
You can typically create a random numpy (40,1) array and still manage to fairly converge it. Does that help?
